Fixed importing errors in tests.
JonnyTran/OpenOmics pull request #167
Opened 2022-09-21 21:46 UTC by sdhutchins

- Simply updated the import for the tests so the tests would at least run (even though there are errors).

I've linked this PR to an issue as well.

2022-09-28 17:00 UTC, JonnyTran approved these changes
These import paths looks good to me.

2022-09-28 17:01 UTC, JonnyTran approved these changes

2022-09-28 17:04 UTC, JonnyTran approved these changes
we might as well remove `generate_LncRNA2Target` since their database is no longer publicly available or actively updated (though I have a copy of their data).

2022-09-28 17:05 UTC, JonnyTran approved these changes
agree with these changes. I've actually made the same updates in master as well

2022-09-28 17:14 UTC, JonnyTran requested changes
This had an error at `index="gene_name"` because I recently changed the function to take in a `list` or `pd.Index` of gene ids/names, not just the string of `index name`.
I'd still keep `data.initialize_annotations()` if possible, since we need make sure `data.annotations` df gets instantiated. In the future we might want `MessengerRNA.__init__()` to automatically run `initialize_annotations()` so the users doesn't have to remember run it before they `.annotate_attributes()`.

2022-09-28 17:16 UTC, JonnyTran commented on tests/test_multiomics.py
> -    data.initialize_annotations(index="gene_name", )
see https://github.com/JonnyTran/OpenOmics/pull/167#pullrequestreview-1124082309

2022-10-10 17:23 UTC, merged

2022-10-11 19:44 UTC, sdhutchins commented
Hey! I'm going to work more on the testing and whatnot. Grad school got me sidetracked a bit! Excited to work more on this.

2022-10-12 00:11 UTC, JonnyTran commented
> Hey! I'm going to work more on the testing and whatnot. Grad school got me sidetracked a bit! Excited to work more on this.

No problem, totally understand! This is a side project of mine too, but I'm so glad you're interested on working on it!

As far as the current development state, I make new contributions to OpenOmics whenever I need it to do something to support my research work. But, I'm hoping to learn more about how others (like you) uses it for your own research, so it'll be more useful for the overall bioinf research community. 

When you have time, can you list some new features you'd like to see or pain-points you'd like to be fixed? I've made a project board at https://github.com/JonnyTran/OpenOmics/projects/2. You can drop a TODO list there, and I'll go over it.

If you'd like to chat over a Slack group, I can make one too!

2023-06-16 23:35 UTC, sdhutchins commented
Hey @JonnyTran - I had some life stuff happen, but I am back into things now. If you have an PRs or whatnot that you want reviewed, feel free to send them my way as well. I'd love to discuss more on how I'm using this in my work.

2023-07-01 17:20 UTC, JonnyTran commented
Thank you @sdhutchins, let me know you need anything, especially with access to certain databases or certain analytic use cases. I haven't been contributing to the package recently but will get back to it. I can send you an email with a few survey question on usability and user experiences, and we can follow up from there.